applications:
    myapp:
        ...
        web:
            commands:
                start: "gunicorn -b unix:$SOCKET config.wsgi"
            upstream:
                socket_family: unix

            locations:
                "/":
                    "passthru": true
                "/static":
                    "allow": true
                    "expires": "1h"

        build: |
                set -eux
                pip install --upgrade pip
                pip install -r requirements.txt

        deploy: |
          set -eux

          python manage.py collectstatic --noinput
          python manage.py migrate

        mounts:
          "/staticfiles":
            source: "local"
            source_path: "static_assets"
